### ISSUE TITLE
batch upload policy

### ISSUE THREAD

**Issue by HadiModarres** [HadiModarres/s3_uploader_service#3]
Make a configuration for upload policy that makes the script upload many files at once. 

Policies supported: 
1- A number of files (like 40) -> would scan and upload this number of files  
2- Exhaustive -> would scan and upload everything it finds

**Comment by ghost** [comment]
One problem here.
Scan and upload are two separate operations, e.g. first we scan all files that match the criteria, then we walk them all and upload them.

Where does the limitation happen, in the number of scanned files or the number of uploaded?

# Case: scanned

If we limit to scan up to, say, 40 files at a time, we will always end up scanning the first 40 files, that most probably, would have already been uploaded.

# Case: uploaded

This is fine as depending on the Rewrite Policy from #4 we can only count the successfully uploaded files, however, we will need to scan **all** of the files in the previous step so that we would have enough files to upload in case a lot are already uploaded and are skipped in the upload step.

If the rewrite policy says rewrite though, we will be stuck at the first 40 files being scanned and uploaded over and over again and we will never proceed past them.

P.S. I just realized, the above is only an issue if `--delete` is not set, otherwise uploaded files would have been deleted locally and wouldn't be included in the scan in the first place.

**Comment by ghost** [comment]
I'm not really sure when we would not be using `--delete` to be honest. In this case I would vote for the first case - we limit the number of scanned files.

After all we want to get rid of local eligible files 40 at a time. Even if they exist remotely and are not to be uploaded, we still consider them as "processed" and delete them locally.

**Comment by ghost** [comment]
Use `--limit=40` to specify a maximum number of files to be scanned.

**Comment by HadiModarres** [comment]
I think it would be up to the user to provide a sensible configuration. We could be using this without --delete at some point to do a backup for example.

**Comment by HadiModarres** [comment]
I'll test this thanks

**Comment by HadiModarres** [comment]
works as expected
